//! STARK Proof System for QuantumHarmony Blockchain
//!
//! This module defines a flexible STARK proof architecture for various operations:
//! - **Quantum Entropy**: Reporter QRNG measurements
//! - **Validator Votes**: Coherence consensus participation
//! - **Finality Proofs**: Block finalization justifications
//! - **Transactions**: Privacy-preserving transfers
//! - **State Transitions**: Runtime execution correctness
//! - **Cross-Chain**: Bridge message authenticity
//!
//! ## Architecture
//!
//! Each proof type follows the same pattern:
//! 1. Off-chain computation generates a STARK proof (Winterfell)
//! 2. Proof is submitted to chain with public inputs
//! 3. On-chain verifier checks proof validity
//! 4. Result is stored/used for consensus/finality
//!
//! ## Security Properties
//!
//! - **Zero-Knowledge**: Proofs reveal nothing about private witness data
//! - **Succinctness**: Proofs are O(log n) size in circuit complexity
//! - **Post-Quantum Security**: STARK proofs resist quantum attacks (hash-based)
//! - **Public Verifiability**: Anyone can verify proofs on-chain
//! - **Soundness**: Cheating provers are detected with high probability

use codec::{Decode, Encode};
use scale_info::TypeInfo;
use sp_core::H256;
use sp_std::vec::Vec;

/// STARK Proof Type Discriminator
///
/// Identifies which type of computation/statement the STARK proof is proving.
/// Each type has different public inputs and verification logic.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub enum StarkProofType {
    /// Proof of quantum entropy collection from QRNG + QKD
    QuantumEntropy,

    /// Proof that a validator correctly computed coherence scores
    ValidatorVote,

    /// Proof of >2/3 validator supermajority for finality
    FinalityJustification,

    /// Privacy-preserving transaction proof (amounts hidden)
    PrivateTransaction,

    /// Proof that state transition followed runtime rules
    StateTransition,

    /// Proof that a cross-chain message is authentic
    CrossChainMessage,

    /// Proof of correct smart contract execution
    ContractExecution,

    /// Proof of ML model inference (for AI pallets)
    MlInference,
}

/// Generic STARK Proof Container
///
/// This is a flexible container that can hold any type of STARK proof.
/// The `proof_type` field determines how to interpret the public inputs.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct StarkProof<AccountId> {
    /// What type of computation this proof is demonstrating
    pub proof_type: StarkProofType,

    /// STARK proof bytes (generated by Winterfell)
    pub stark_proof: Vec<u8>,

    /// Public inputs (format depends on proof_type)
    /// Encoded as SCALE bytes for flexibility
    pub public_inputs_raw: Vec<u8>,

    /// Submitter's signature (Falcon1024 or SPHINCS+)
    pub signature: Vec<u8>,

    /// Submitter account
    pub submitter: AccountId,

    /// Unix timestamp (milliseconds)
    pub timestamp: u64,
}

/// STARK proof of quantum entropy collection
///
/// This structure contains a zero-knowledge proof that a reporter has:
/// 1. Collected quantum entropy from authorized hardware (QRNG)
/// 2. Measured QBER from QKD network and verified it's < 11%
/// 3. Used authentic QKD keys for secure transmission
/// 4. Signed the proof with their authorized Falcon1024 key
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct QuantumEntropyProof<AccountId> {
    /// STARK proof bytes (generated by Winterfell)
    /// This is a succinct proof of the quantum entropy collection circuit
    pub stark_proof: Vec<u8>,

    /// Public inputs to the STARK proof
    /// These are the committed values that validators can verify
    pub public_inputs: PublicInputs<AccountId>,

    /// Reporter's Falcon1024 signature over the proof
    /// Signs: hash(stark_proof || public_inputs || timestamp)
    pub signature: Vec<u8>,

    /// Unix timestamp (milliseconds) when the measurement was taken
    /// Used for:
    /// - Freshness verification (reject old proofs)
    /// - Temporal correlation analysis
    /// - QBER drift detection
    pub timestamp: u64,
}

/// Public inputs to the STARK proof
///
/// These values are committed to in the proof and can be verified by anyone.
/// The actual quantum measurements remain private (zero-knowledge property).
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct PublicInputs<AccountId> {
    /// Hash commitment to the quantum entropy samples
    ///
    /// commitment = H(QRNG_samples || nonce || reporter_id)
    ///
    /// This binds the proof to specific entropy without revealing it.
    /// The actual samples are kept off-chain in encrypted SPQR channels.
    pub entropy_commitment: H256,

    /// Quantum Bit Error Rate measurement (scaled by 10,000)
    ///
    /// Examples:
    /// - 5.5% QBER = 550
    /// - 11% QBER = 1100 (maximum threshold)
    /// - 0.1% QBER = 10
    ///
    /// SECURITY THRESHOLD: Must be < 1100 (11%)
    ///
    /// If QBER >= 11%, the QKD channel may be compromised by eavesdropping.
    /// The STARK proof must demonstrate QBER was measured and is below threshold.
    pub qber: u32,

    /// QKD key identifier used for this measurement
    ///
    /// This references a specific quantum-distributed key from the IDQ system.
    /// Format: SHA256 hash of the key material or hardware key ID
    ///
    /// Validators can verify:
    /// - The key exists in SecureQkdKeys storage
    /// - The key was distributed via authentic QKD
    /// - The key has not expired or been compromised
    pub qkd_key_id: Vec<u8>,

    /// Reporter account who generated this proof
    ///
    /// Must be an authorized reporter (in AuthorizedReporters storage).
    /// This binds the proof to a specific KYC/KYE-verified entity.
    pub reporter: AccountId,

    /// Number of QRNG samples included in this proof
    ///
    /// Minimum required: 256 samples (for statistical significance)
    /// Typical: 1024-4096 samples
    ///
    /// More samples = higher entropy quality but larger proof size.
    pub sample_count: u32,

    /// Hash of the quantum hardware attestation certificate
    ///
    /// This proves the reporter is using genuine quantum hardware:
    /// - IDQ Quantis QRNG
    /// - Crypto4A HSM with QRNG
    /// - IDQ QKD system
    ///
    /// The certificate is issued by the hardware manufacturer and includes:
    /// - Device serial number
    /// - Calibration data
    /// - Tamper-evident signatures
    pub hardware_attestation: H256,
}

/// Result of verifying a quantum entropy proof
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
pub enum ProofVerificationResult {
    /// Proof is valid and meets all requirements
    Valid,

    /// STARK proof verification failed (invalid cryptographic proof)
    InvalidStarkProof,

    /// QBER exceeds 11% threshold (possible eavesdropping)
    QberTooHigh,

    /// QKD key ID not found in storage
    UnknownQkdKey,

    /// Reporter signature verification failed (not Falcon1024)
    InvalidSignature,

    /// Reporter is not in authorized list
    UnauthorizedReporter,

    /// Timestamp is too old (> 24 hours)
    StaleProof,

    /// Sample count below minimum (< 256)
    InsufficientSamples,

    /// Hardware attestation invalid or not recognized
    InvalidHardwareAttestation,
}

/// Aggregated proof for batch finalization
///
/// Instead of finalizing each block individually, we batch multiple proofs
/// together and generate a single aggregated proof for efficiency.
///
/// This is the quantum coherence equivalent of GRANDPA's batch finalization.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct AggregatedQuantumProof<AccountId, BlockNumber, Hash> {
    /// Individual STARK proofs from reporters
    pub proofs: Vec<QuantumEntropyProof<AccountId>>,

    /// Block range being finalized
    pub from_block: BlockNumber,
    pub to_block: BlockNumber,

    /// Hash of the last block being finalized
    pub finalized_block_hash: Hash,

    /// Total coherence score across all proofs
    ///
    /// coherence_score = Σ(1 / (1 + QBER_i)) for all valid proofs
    ///
    /// Higher score = better quantum quality
    /// Minimum threshold: Determined by governance
    pub total_coherence_score: u64,

    /// Number of validators who signed this aggregated proof
    pub validator_count: u32,

    /// Combined validator signatures (Falcon1024)
    /// Each validator signs: hash(proofs || from_block || to_block || coherence_score)
    pub validator_signatures: Vec<Vec<u8>>,

    /// Timestamp when aggregation was performed
    pub aggregation_timestamp: u64,
}

// ============================================================================
// EXAMPLE: Additional STARK Proof Types for Different Chain Operations
// ============================================================================

/// Public inputs for ValidatorVote STARK proof
///
/// Proves that a validator correctly:
/// - Collected N quantum entropy proofs from reporters
/// - Verified each proof's STARK, QBER, signature, etc.
/// - Calculated coherence score according to formula
/// - Did not tamper with results
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct ValidatorVoteInputs<AccountId, BlockHash> {
    /// The validator who is voting
    pub validator: AccountId,

    /// Block being voted on
    pub block_hash: BlockHash,

    /// Number of proofs verified
    pub proofs_verified: u32,

    /// Number of proofs rejected
    pub proofs_rejected: u32,

    /// Computed coherence score
    pub coherence_score: u64,

    /// Hash of all verified proof commitments
    /// commitment = H(proof_1 || proof_2 || ... || proof_n)
    pub proofs_merkle_root: H256,

    /// Vote type (Prevote or Precommit)
    pub vote_round: u8, // 0 = Prevote, 1 = Precommit
}

/// Public inputs for PrivateTransaction STARK proof
///
/// Proves that a transaction is valid without revealing amounts:
/// - Sender has sufficient balance
/// - Amount > 0
/// - No overflow/underflow
/// - Recipient address is valid
///
/// This enables privacy-preserving transfers on QuantumHarmony.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct PrivateTransactionInputs<AccountId> {
    /// Commitment to sender's old balance
    /// old_balance_commitment = H(old_balance || sender || nonce)
    pub old_balance_commitment: H256,

    /// Commitment to sender's new balance
    /// new_balance_commitment = H(new_balance || sender || nonce+1)
    pub new_balance_commitment: H256,

    /// Commitment to recipient's new balance
    pub recipient_new_balance_commitment: H256,

    /// Range proof that amount > 0 and < MAX
    pub amount_range_proof_commitment: H256,

    /// Sender and recipient (public for auditing)
    pub sender: AccountId,
    pub recipient: AccountId,

    /// Transaction nonce
    pub nonce: u64,
}

/// Public inputs for StateTransition STARK proof
///
/// Proves that runtime executed extrinsics correctly:
/// - State root transitioned validly
/// - All extrinsics in block were valid
/// - Storage changes match execution
/// - No unauthorized state mutations
///
/// This could be used for rollups or fraud proofs.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct StateTransitionInputs<BlockHash> {
    /// Pre-state root (before block execution)
    pub pre_state_root: H256,

    /// Post-state root (after block execution)
    pub post_state_root: H256,

    /// Block hash
    pub block_hash: BlockHash,

    /// Number of extrinsics executed
    pub extrinsics_count: u32,

    /// Merkle root of all extrinsic results
    pub extrinsics_root: H256,

    /// Runtime version that executed this block
    pub runtime_version: u32,
}

/// Public inputs for CrossChainMessage STARK proof
///
/// Proves that a message from another chain is authentic:
/// - Source chain finalized the message
/// - Message was included in source block
/// - Relay validators signed the message
/// - Message has not been replayed
///
/// This enables secure bridges between QuantumHarmony and other chains.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct CrossChainMessageInputs<AccountId> {
    /// Hash of the source chain block containing the message
    pub source_block_hash: H256,

    /// Source chain ID
    pub source_chain_id: u32,

    /// Destination chain ID (this chain)
    pub dest_chain_id: u32,

    /// Merkle proof that message was in source block
    pub inclusion_proof_commitment: H256,

    /// Number of relay validators who signed
    pub relay_signer_count: u32,

    /// Threshold required (>2/3)
    pub relay_threshold: u32,

    /// Message hash
    pub message_hash: H256,

    /// Message sender on source chain
    pub sender: AccountId,

    /// Message nonce (prevents replay)
    pub nonce: u64,
}

/// Verification result for generic STARK proofs
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
pub enum StarkVerificationResult {
    /// Proof is valid
    Valid,

    /// STARK proof cryptographic verification failed
    InvalidStarkProof,

    /// Public inputs don't match expected format
    InvalidPublicInputs,

    /// Signature verification failed
    InvalidSignature,

    /// Proof is too old (> max age)
    Stale,

    /// Proof type not supported
    UnsupportedProofType,

    /// Custom error with message
    Custom(Vec<u8>),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_qber_threshold() {
        // 11% QBER is the maximum
        let max_qber = 1100u32;
        assert_eq!(max_qber, 1100);

        // 10.99% should be valid
        let valid_qber = 1099u32;
        assert!(valid_qber < 1100);

        // 11.01% should be invalid
        let invalid_qber = 1101u32;
        assert!(invalid_qber >= 1100);
    }

    #[test]
    fn test_minimum_samples() {
        // Minimum 256 samples required
        let min_samples = 256u32;
        assert_eq!(min_samples, 256);

        // 255 samples should be rejected
        assert!(255u32 < 256);

        // 256 samples should be valid
        assert!(256u32 >= 256);
    }
}
