//! STARK Proof Structures for Quantum Entropy
//!
//! This module defines the data structures for Zero-Knowledge STARK proofs
//! that demonstrate valid quantum entropy collection from authorized reporters.
//!
//! ## Architecture
//!
//! Reporters with quantum hardware (QRNG, QKD) collect entropy and generate
//! STARK proofs using the Winterfell library. These proofs are then submitted
//! to the blockchain where validators can verify them without revealing the
//! actual quantum measurements.
//!
//! ## Security Properties
//!
//! - **Zero-Knowledge**: Proofs reveal nothing about the quantum measurements
//! - **Succinctness**: Proofs are much smaller than the witness data
//! - **Post-Quantum Security**: STARK proofs resist quantum attacks
//! - **Public Verifiability**: Anyone can verify proofs on-chain

use codec::{Decode, Encode};
use scale_info::TypeInfo;
use sp_core::H256;
use sp_std::vec::Vec;

/// STARK proof of quantum entropy collection
///
/// This structure contains a zero-knowledge proof that a reporter has:
/// 1. Collected quantum entropy from authorized hardware (QRNG)
/// 2. Measured QBER from QKD network and verified it's < 11%
/// 3. Used authentic QKD keys for secure transmission
/// 4. Signed the proof with their authorized Falcon1024 key
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct QuantumEntropyProof<AccountId> {
    /// STARK proof bytes (generated by Winterfell)
    /// This is a succinct proof of the quantum entropy collection circuit
    pub stark_proof: Vec<u8>,

    /// Public inputs to the STARK proof
    /// These are the committed values that validators can verify
    pub public_inputs: PublicInputs<AccountId>,

    /// Reporter's Falcon1024 signature over the proof
    /// Signs: hash(stark_proof || public_inputs || timestamp)
    pub signature: Vec<u8>,

    /// Unix timestamp (milliseconds) when the measurement was taken
    /// Used for:
    /// - Freshness verification (reject old proofs)
    /// - Temporal correlation analysis
    /// - QBER drift detection
    pub timestamp: u64,
}

/// Public inputs to the STARK proof
///
/// These values are committed to in the proof and can be verified by anyone.
/// The actual quantum measurements remain private (zero-knowledge property).
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct PublicInputs<AccountId> {
    /// Hash commitment to the quantum entropy samples
    ///
    /// commitment = H(QRNG_samples || nonce || reporter_id)
    ///
    /// This binds the proof to specific entropy without revealing it.
    /// The actual samples are kept off-chain in encrypted SPQR channels.
    pub entropy_commitment: H256,

    /// Quantum Bit Error Rate measurement (scaled by 10,000)
    ///
    /// Examples:
    /// - 5.5% QBER = 550
    /// - 11% QBER = 1100 (maximum threshold)
    /// - 0.1% QBER = 10
    ///
    /// SECURITY THRESHOLD: Must be < 1100 (11%)
    ///
    /// If QBER >= 11%, the QKD channel may be compromised by eavesdropping.
    /// The STARK proof must demonstrate QBER was measured and is below threshold.
    pub qber: u32,

    /// QKD key identifier used for this measurement
    ///
    /// This references a specific quantum-distributed key from the IDQ system.
    /// Format: SHA256 hash of the key material or hardware key ID
    ///
    /// Validators can verify:
    /// - The key exists in SecureQkdKeys storage
    /// - The key was distributed via authentic QKD
    /// - The key has not expired or been compromised
    pub qkd_key_id: Vec<u8>,

    /// Reporter account who generated this proof
    ///
    /// Must be an authorized reporter (in AuthorizedReporters storage).
    /// This binds the proof to a specific KYC/KYE-verified entity.
    pub reporter: AccountId,

    /// Number of QRNG samples included in this proof
    ///
    /// Minimum required: 256 samples (for statistical significance)
    /// Typical: 1024-4096 samples
    ///
    /// More samples = higher entropy quality but larger proof size.
    pub sample_count: u32,

    /// Hash of the quantum hardware attestation certificate
    ///
    /// This proves the reporter is using genuine quantum hardware:
    /// - IDQ Quantis QRNG
    /// - Crypto4A HSM with QRNG
    /// - IDQ QKD system
    ///
    /// The certificate is issued by the hardware manufacturer and includes:
    /// - Device serial number
    /// - Calibration data
    /// - Tamper-evident signatures
    pub hardware_attestation: H256,
}

/// Result of verifying a quantum entropy proof
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
pub enum ProofVerificationResult {
    /// Proof is valid and meets all requirements
    Valid,

    /// STARK proof verification failed (invalid cryptographic proof)
    InvalidStarkProof,

    /// QBER exceeds 11% threshold (possible eavesdropping)
    QberTooHigh,

    /// QKD key ID not found in storage
    UnknownQkdKey,

    /// Reporter signature verification failed (not Falcon1024)
    InvalidSignature,

    /// Reporter is not in authorized list
    UnauthorizedReporter,

    /// Timestamp is too old (> 24 hours)
    StaleProof,

    /// Sample count below minimum (< 256)
    InsufficientSamples,

    /// Hardware attestation invalid or not recognized
    InvalidHardwareAttestation,
}

/// Aggregated proof for batch finalization
///
/// Instead of finalizing each block individually, we batch multiple proofs
/// together and generate a single aggregated proof for efficiency.
///
/// This is the quantum coherence equivalent of GRANDPA's batch finalization.
#[derive(Clone, Encode, Decode, TypeInfo, PartialEq, Eq, Debug)]
#[cfg_attr(feature = "std", derive(serde::Serialize, serde::Deserialize))]
pub struct AggregatedQuantumProof<AccountId, BlockNumber, Hash> {
    /// Individual STARK proofs from reporters
    pub proofs: Vec<QuantumEntropyProof<AccountId>>,

    /// Block range being finalized
    pub from_block: BlockNumber,
    pub to_block: BlockNumber,

    /// Hash of the last block being finalized
    pub finalized_block_hash: Hash,

    /// Total coherence score across all proofs
    ///
    /// coherence_score = Σ(1 / (1 + QBER_i)) for all valid proofs
    ///
    /// Higher score = better quantum quality
    /// Minimum threshold: Determined by governance
    pub total_coherence_score: u64,

    /// Number of validators who signed this aggregated proof
    pub validator_count: u32,

    /// Combined validator signatures (Falcon1024)
    /// Each validator signs: hash(proofs || from_block || to_block || coherence_score)
    pub validator_signatures: Vec<Vec<u8>>,

    /// Timestamp when aggregation was performed
    pub aggregation_timestamp: u64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_qber_threshold() {
        // 11% QBER is the maximum
        let max_qber = 1100u32;
        assert_eq!(max_qber, 1100);

        // 10.99% should be valid
        let valid_qber = 1099u32;
        assert!(valid_qber < 1100);

        // 11.01% should be invalid
        let invalid_qber = 1101u32;
        assert!(invalid_qber >= 1100);
    }

    #[test]
    fn test_minimum_samples() {
        // Minimum 256 samples required
        let min_samples = 256u32;
        assert_eq!(min_samples, 256);

        // 255 samples should be rejected
        assert!(255u32 < 256);

        // 256 samples should be valid
        assert!(256u32 >= 256);
    }
}
