//! Autogenerated weights for `pallet_quantum_crypto`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_quantum_crypto`.
pub trait WeightInfo {
	fn store_entropy() -> Weight;
	fn set_quantum_key() -> Weight;
	fn generate_quantum_signature() -> Weight;
}

/// Weights for `pallet_quantum_crypto` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: QuantumCrypto EntropyPool (r:0 w:1)
	/// Proof: QuantumCrypto EntropyPool (max_values: Some(1), max_size: Some(1024), added: 1519, mode: MaxEncodedLen)
	fn store_entropy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 5_000 picoseconds.
		Weight::from_parts(6_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	
	/// Storage: QuantumCrypto QuantumKeys (r:0 w:1)
	/// Proof: QuantumCrypto QuantumKeys (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn set_quantum_key() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000 picoseconds.
		Weight::from_parts(9_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
	
	/// Storage: QuantumCrypto SignatureProofs (r:0 w:1)
	/// Proof: QuantumCrypto SignatureProofs (max_values: None, max_size: Some(49920), added: 52395, mode: MaxEncodedLen)
	fn generate_quantum_signature() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 100_000 picoseconds.
		Weight::from_parts(150_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility
impl WeightInfo for () {
	fn store_entropy() -> Weight {
		Weight::from_parts(6_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	
	fn set_quantum_key() -> Weight {
		Weight::from_parts(9_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	
	fn generate_quantum_signature() -> Weight {
		Weight::from_parts(150_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}